name: 'LGM_TEST'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        #uses: joonvena/robotframework-docker-action@v0.1
        run: |
          mkdir ${{github.workspace}}/reports
          docker run --shm-size=1g -e BROWSER=headlesschrome \
          -v ${{github.workspace}}/lgm-front:/opt/robotframework/tests:Z \
          -v ${{github.workspace}}/reports:/opt/robotframework/reports:Z \
          -v ${{github.workspace}}/resources:/opt/robotframework/resources:Z \
          --user 1001:1000 \
          ppodgorsek/robot-framework:latest
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/lgm-front
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
          REPORT_PATH: ${{ github.workspace }}/reports
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports